# Generated by Django 5.2.17 on 2026-08-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='christiangift44@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+1 603 322 0842', max_length=30)),
                ('github_url', models.URLField(default='https://github.com/gcl140')),
                ('linkedin_url', models.URLField(default='https://linkedin.com/in/giftchristian')),
                ('instagram_url', models.URLField(default='https://instagram.com/gcl.140')),
                ('resume_url', models.CharField(default='/resume.pdf', max_length=255)),
            ],
            options={
                'verbose_name': 'Contact info',
                'verbose_name_plural': 'Contact info',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emailed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome class', max_length=60)),
                ('image', models.ImageField(upload_to='interests/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(default=2021, help_text="Used to compute 'years of experience'")),
                ('happy_clients', models.PositiveIntegerField(default=8)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('icon', models.CharField(help_text="Font Awesome class, e.g. 'fab fa-python'", max_length=60)),
                ('category', models.CharField(choices=[('framework', 'Framework'), ('tool', 'Tool')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=3, help_text='1-5, how strong this skill is')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField(help_text='Live URL, often a subdomain of giftchristian.dev')),
                ('code_url', models.URLField(blank=True, verbose_name='code URL')),
                ('image', models.URLField(help_text='Cover image URL')),
                ('project_type', models.CharField(choices=[('fullstack', 'Full-stack'), ('django', 'Django'), ('frontend', 'Frontend'), ('academic', 'Academic')], default='fullstack', max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('skills', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.skill')),
            ],
            options={
                'ordering': ['order', '-year', 'name'],
            },
        ),
    ]
