# Generated by Django 5.2.17 on 2026-08-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_contactinfo_resume_url_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('graduation_year', models.CharField(max_length=20)),
                ('degree', models.CharField(blank=True, max_length=200)),
                ('gpa', models.CharField(blank=True, max_length=30)),
                ('coursework', models.TextField(blank=True, help_text='Comma-separated list')),
                ('activities', models.TextField(blank=True, help_text='Comma-separated list')),
                ('award', models.CharField(blank=True, max_length=255)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-graduation_year'],
            },
        ),
    ]
