# Generated by Django 5.2.17 on 2026-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('tool', 'Tool')], max_length=20),
        ),
    ]
