# Generated by Django 5.2.17 on 2026-08-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='SDE Intern, Evergreen AI', max_length=120)),
                ('location', models.CharField(default='Hanover, NH', max_length=120)),
                ('bio', models.TextField(default='', help_text='Separate paragraphs with a blank line.')),
            ],
            options={
                'verbose_name': 'About me',
                'verbose_name_plural': 'About me',
            },
        ),
    ]
