# Generated by Django 5.2.17 on 2026-08-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Upload a cover image. Takes priority over the URL below if both are set.', null=True, upload_to='projects/', verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, help_text='Cover image URL, used only if no image is uploaded above.', verbose_name='cover image URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Position in the pipeline. Saving with an order that's already taken bumps that item and everything after it up by one."),
        ),
    ]
